name: streamflows
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adjusttext=1.3.0
  - affine=2.4.0
  - alsa-lib=1.2.14
  - asttokens=3.0.0
  - attrs=25.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - blosc=1.21.5
  - boost-cpp=1.74.0
  - branca=0.8.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=4.0.0
  - charset-normalizer=3.4.3
  - click=8.1.8
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - comm=0.2.3
  - contextily=1.6.2
  - contourpy=1.3.0
  - curl=7.86.0
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.8.16
  - decorator=5.2.1
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.3
  - fiona=1.8.20
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.4.0
  - geographiclib=2.0
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geopy=2.4.1
  - geos=3.10.1
  - geotiff=1.7.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.5
  - h2=4.2.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - hpack=4.1.0
  - html5lib=1.1
  - hyperframe=6.1.0
  - icu=68.2
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - json-c=0.15
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kealib=1.4.15
  - keyutils=1.6.3
  - kiwisolver=1.4.7
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang=11.1.0
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal=3.4.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.80.2
  - libgomp=15.2.0
  - libiconv=1.18
  - libkml=1.3.0
  - liblapack=3.11.0
  - libllvm11=11.1.0
  - libllvm13=13.0.1
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libpng=1.6.43
  - libpq=13.5
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=2.1.0
  - libspatialite=5.0.1
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.4.0
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mechanize=0.4.10
  - mercantile=1.2.1
  - munch=4.0.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nspr=4.38
  - nss=3.100
  - numpy=1.26.4
  - openjpeg=2.5.0
  - openpyxl=3.1.5
  - openssl=1.1.1w
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pcre=8.45
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - poppler=21.11.0
  - poppler-data=0.4.12
  - postgresql=13.5
  - proj=8.2.0
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt=5.12.9
  - rasterio=1.2.10
  - readline=8.2
  - requests=2.32.5
  - rtree=1.4.1
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=80.9.0
  - shapely=1.8.0
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.46.0
  - stack_data=0.6.3
  - threadpoolctl=3.6.0
  - tiledb=2.5.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzcode=2025b
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2025.11.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /home/benr/mambaforge/envs/streamflows
